image:
  file: gitpod.Dockerfile
ports:
  - port: 8080
tasks:
  - init: >
      npm ci --no-optional --no-audit --progress=false &&
      poetry install &&
      npm run build:prod &&
      python manage.py collectstatic --noinput --clear &&
      python manage.py migrate &&
      DJANGO_SUPERUSER_PASSWORD=changeme
      python manage.py createsuperuser --noinput --username admin --email admin@example.com
    command: python manage.py runserver 0.0.0.0:8080
